### ISSUE TITLE
Transcribe mp4 files

### ISSUE THREAD

**Issue by ZeusLT** [BBC-Esq/WhisperS2T-transcriber#2]
Is it feasible to enable direct reading of the AAC format from mp4 files? This would eliminate an intermediate step and potentially save time for some workflows.

**Comment by BBC-Esq** [comment]
I've toyed with the idea, just haven't gotten around to it yet.  Will take another look to see how difficult it'd be.  Just to clarify, you're referring to being able to process the audio stream - if any - from an .mp4 video file/files?

**Comment by ZeusLT** [comment]
Yes. I'm sure there are ton of other video formats that could use the same treatment, but personally my eyes are on mp4 as I work a lot with twitch VODs, which brings me another question, I don't really want to start a new issue just for this question. So at the moment it generates text chunks of 150 to 500 char long that last from a few seconds to over a minute (as subtitles), is there a way to generate them in smaller chunks?

**Comment by BBC-Esq** [comment]
Cool!  The whisperS2T library that the batch transcriber uses relies on ffmpeg I believe, so it could very well just extract the audio stream from a video file that has both an audio and video stream?  Or did you just have an .mp4 file with ONLY an audio stream?  If it's the former, I can just modify the script to also support .mp4 without doing anything else!   Either way, is it safe to close out this issue?

**Comment by ZeusLT** [comment]
It had both audio and video. Yeah I will close it.
