### ISSUE TITLE
ffmpeg failed to resample the input audio file

### ISSUE THREAD

**Issue by ZeusLT** [BBC-Esq/WhisperS2T-transcriber#3]
Updated to 1.1.0 and now it fails:

```
Fetching 4 files: 100%|██████████████████████████████████████████████████████████████████████████| 4/4 [00:00<?, ?it/s]
Transcribing:   0%|                                                                            | 0/100 [00:00<?, ?it/s]
Error processing file J:\2. Archive\6. Audio Only\1.wav: ffmpeg failed to resample the input audio file, make sure ffmpeg is compiled properly! (1/3)
Transcribing:   0%|                                                                            | 0/100 [00:00<?, ?it/s]
Error processing file J:\2. Archive\6. Audio Only\2.wav: ffmpeg failed to resample the input audio file, make sure ffmpeg is compiled properly! (2/3)
Transcribing:   0%|                                                                            | 0/100 [00:00<?, ?it/s]
Error processing file J:\2. Archive\6. Audio Only\3.wav: ffmpeg failed to resample the input audio file, make sure ffmpeg is compiled properly! (3/3)
```
I have ffmpeg in my PATH environment variables. I tried to `pip install ffmpeg` didn't work either.

Using `ffmpeg` in cmd just works.

`ffmpeg -version`:
ffmpeg version N-111833-gb5273c619d-20230828 Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 13.1.0 (crosstool-NG 1.25.0.196_227d99d)

**Comment by BBC-Esq** [comment]
Thanks for the feedback.  Can you confirm/disconfirm whether version 1.0.0 was working with the exact same 3 files?  They just might have not been processing before is what I need to doublecheck...

**Comment by ZeusLT** [comment]
Okay I tried v1 scripts, everything failed, these 3 files and the old ones that used to work, it must be my packages failing. 

```
Traceback (most recent call last):
  File "J:\Applications\AI\Audio\Voice\WhisperS2T-transcriber\venv\lib\site-packages\whisper_s2t\audio.py", line 32, in load_audio
    with wave.open(input_file, 'rb') as wf:
  File "C:\Users\ZeusLT\AppData\Local\Programs\Python\Python310\lib\wave.py", line 509, in open
    return Wave_read(f)
  File "C:\Users\ZeusLT\AppData\Local\Programs\Python\Python310\lib\wave.py", line 163, in __init__
    self.initfp(f)
  File "C:\Users\ZeusLT\AppData\Local\Programs\Python\Python310\lib\wave.py", line 130, in initfp
    raise Error('file does not start with RIFF id')
wave.Error: file does not start with RIFF id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "J:\Applications\AI\Audio\Voice\WhisperS2T-transcriber\whispers2t_batch_transcriber.py", line 49, in run
    out = model.transcribe_with_vad(audio_files_str, lang_codes=lang_codes, tasks=tasks, initial_prompts=initial_prompts, batch_size=self.batch_size)
  File "J:\Applications\AI\Audio\Voice\WhisperS2T-transcriber\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "J:\Applications\AI\Audio\Voice\WhisperS2T-transcriber\venv\lib\site-packages\whisper_s2t\backends\__init__.py", line 169, in transcribe_with_vad
    for signals, prompts, seq_len, seg_metadata, pbar_update in self.data_loader(audio_files, lang_codes, tasks, initial_prompts, batch_size=batch_size):
  File "J:\Applications\AI\Audio\Voice\WhisperS2T-transcriber\venv\lib\site-packages\whisper_s2t\data.py", line 212, in get_data_loader_with_vad
    for file_id, (audio_signal, lang, task, initial_prompt) in enumerate(zip(audio_batch_generator(audio_files), lang_codes, tasks, initial_prompts)):
  File "C:\Users\ZeusLT\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 873, in next
    raise value
  File "C:\Users\ZeusLT\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "J:\Applications\AI\Audio\Voice\WhisperS2T-transcriber\venv\lib\site-packages\whisper_s2t\audio.py", line 42, in load_audio
    if ret_code != 0: raise RuntimeError("ffmpeg failed to resample the input audio file, make sure ffmpeg is compiled properly!")
RuntimeError: ffmpeg failed to resample the input audio file, make sure ffmpeg is compiled properly!
```

Let me try to re-setup v1 from scratch.

**Comment by BBC-Esq** [comment]
It's normal to get some errors when processing lots of files, even I get some depending on the quality of the audio.  I plan on working out the kinks...right now it's about a 5% fail rate, so 5 files fail for every 100 I try to process.  Not sure if that's an issue with the WhisperS2T library itself or there's just a problem with these audio files on my computer that have been stored for years...and might not be good quality to begin with...partially downloaded, etc.

But yes, if you can't get anything to work whatsoever, that's different...Let me know...

**Comment by ZeusLT** [comment]
I've set up v1.1.0 again with:
```
python -m venv venv
.\venv\Scripts\activate
python -m pip install --upgrade pip
.\setup_windows.py
```
Worked like a charm this time. Last time I had a different torch version and ran setup_windows.py after basically installing it manually so it mixed libs causing something to fail in the process.

**Comment by BBC-Esq** [comment]
In case someone else encounters a similar issue, are you saying that you manually installed a different version of Pytorch after running ```setup_windows.py``` or what?  I included the appropriate torch libraries within the setup script this time intentionally...to  TRY and make it easier.  lol.

**Comment by ZeusLT** [comment]
I'm saying that when it didn't work my venv was not fresh and I ran `setup_windows.py` on top of that, which caused issues.
To make it work you have to set up a new venv and just run `setup_windows.py`.  

>  I included the appropriate torch libraries within the setup script this time intentionally...to TRY and make it easier. lol.

It is easier :D thank you
