### ISSUE TITLE
Missing package in requirements.txt for Ubuntu Linux 22.04 (pynvml)

### ISSUE THREAD

**Issue by elsatch** [BBC-Esq/WhisperS2T-transcriber#4]
I have tried installing this program in Ubuntu Linux 22.04 using the provided requirements.txt and got a message regarding missing package pynvml.

After doing pip install pynvml, I was able to launch the program (yet from ssh, so I could not get the GUI, but it should work nonethless)-

**Comment by BBC-Esq** [comment]
The "pynvml" library is actually named ```nvidia-ml-py==12.535.133``` on pypi.org.  I'm not sure why it's different than the import statement, but just FYI, this is the one I've been using, which, as far as I know, is the official one.
